### ISSUE TITLE
Can't select/open database file on OxygenOS

### ISSUE THREAD

**Issue by Cris--** [Kunzisoft/KeePassDX#1102]
Hi,

first thanks for this great app!

Now the problem. I'm on OxygenOS 11.1.5.5 A11 with an Oneplus Nord and i can't select the database (opens the popup with the action request information). System is stock and rooted with Magisk v23. Nothing debloated or anything else. So the stock file manager and/or Solid Explorer seems not supporting the needed actions. 

what can i do now?

**Comment by J-Jamet** [comment]
You simply do not have a compatible application active on your device.

Normally most devices offer at least one file manager application by default, so I think you have it disabled.

Otherwise you need to choose an application that supports SAF with the Intent ACTION_OPEN_DOCUMENT and ACTION_CREATE_DOCUMENT

https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by Cris--** [comment]
You mean **stock** OxygenOS for Nord didn't support KeePassDX with these actions via the included file manager? Strange!

**Comment by J-Jamet** [comment]
I don't know, I don't have a device with OxygenOS. But are you sure you haven't disabled any pre-installed application?

**Comment by Micha-Btz** [comment]
Hey,
on my LOS 18.1 Pixel 5 the app crashes while open the database. 
[09-14 14:16:30.312 9442:24302 D/UriUtil]

> Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3Asyncthing%2Ffiles%2Fsysiphus.kdbx, modeFlags=3, persistedTime=1624715955190}
> 
> [09-14 14:16:30.330 1759:1847 W/system_server]
> Insufficient pre-allocated space to mmap vdex.
> 
> [09-14 14:16:30.355 5104:5104 I/GoogleInputMethodService]
> GoogleInputMethodService.onFinishInput():3446 
> 
> [09-14 14:16:30.356 5104:5104 I/GoogleInputMethodService]
> GoogleInputMethodService.onStartInput():2028 
> 
> [09-14 14:16:30.356 24308:24331 E/DatabaseUtils]
> Writing exception to parcel
> java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepassxc-file from pid=9442, uid=10208 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
> 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
> 	at com.android.externalstorage.ExternalStorageProvider.enforceReadPermissionInner(ExternalStorageProvider.java:147)
> 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
> 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
> 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
> 	at android.os.Binder.execTransactInternal(Binder.java:1154)
> 	at android.os.Binder.execTransact(Binder.java:1123)
> 
> [09-14 14:16:30.356 9442:9442 W/DocumentFile]
> Failed query: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepassxc-file from pid=9442, uid=10208 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
> 
> [09-14 14:16:30.357 5104:5104 I/DeviceUnlockedTag]
> DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
> 
> [09-14 14:16:30.357 5104:5104 E/IncognitoEntryAccessPointProvider]
> IncognitoEntryAccessPointProvider.onAccessPointsClosed():81 onAccessPointsClosed is called when incognitoModeEnabled=true, accessPointsShowing=false.


Version 3.0 from fdroid. I have Root Explorer and the file explorer delivered with los installed.

**Comment by J-Jamet** [comment]
@Micha-Btz Your message is not related to this issue, please open a new one following the bug pattern.
