### ISSUE TITLE
Cannot use fingerprint feature, i get "Fingerprint problem: null"

### ISSUE THREAD

**Issue by gradinaruvasile** [Kunzisoft/KeePassDX#114]
Hi, i have a Lenovo K6 Power with Lineage OS 15.1 and if i try to use the fingerprint password save option, i get the following toast message:
```
Fingerprint problem: null
```
I have 4 fingerprints enrolled. Other apps, screen unlocking included seem to use the function just fine.

**Comment by J-Jamet** [comment]
Have you tried the procedure of this issue? https://github.com/Kunzisoft/KeePassDX/issues/89

**Comment by gradinaruvasile** [comment]
Yes, i tried clearing the encryption keys.
Do i have to do something in the system fingerprint store?
> you must then recreate the fingerprints for each password.

refers only to the app side?

I  tried putting the password in then touching the sensor. 
What happens is if a **correct** signature is read, i get this error and the fingerprint picture becomes "greyed out" and the sensor no longer functions.
On an incorrect read i get "Fingerprint not recognized" and i can try again.

**Comment by J-Jamet** [comment]
Normally, nothing to do in the system, all the manipulations are in the application. If a valid signature is read and the correct password is filled (with the checkbox checked), the signature of the fingerprint saves and the database opens. Then, if the checkbox is not checked, the fingerprint is enough to open the database. It does not work anymore since the update? Did you try to make a clear data for the application in the system app setting?

**Comment by gradinaruvasile** [comment]
I tried that too. Reinstalled the app. Same issue. I put the password, touch the sensor, fingerprint icon goes gray, same message.

**Comment by J-Jamet** [comment]
In this case, it is not a generic problem but I can't solve it if I can't reproduce it.
Can you tell me which Android version you are using, the model of your device and from which version of KeePass DX the problem is present if it worked before. If you can also provide me the logs it would be cool! :)

**Comment by J-Jamet** [comment]
Mhhh it's weird, there may be fingerprint API methods that are not used by Lineage.

To recover the logs, the easiest way is to go through Android Studio in your computer, connect your phone by usb, and check the live logs in the console. It can be done with ADB, but it is more restrictive to install manually.

**Comment by gradinaruvasile** [comment]
Ok here is a filtered log (filter was "keepass") 
```
05-15 21:22:07.068 482-1568/? E/BufferQueueProducer: [Splash Screen com.android.keepass#0] dequeueBuffer: BufferQueue has been abandoned
05-15 21:22:07.070 2495-2965/? E/ViewRootImpl[keepass]: Could not lock surface
                                                        java.lang.IllegalArgumentException
                                                            at android.view.Surface.nativeLockCanvas(Native Method)
                                                            at android.view.Surface.lockCanvas(Surface.java:318)
                                                            at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3045)
                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:3019)
                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                            at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                            at android.os.Handler.handleCallback(Handler.java:790)
                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                            at android.os.Looper.loop(Looper.java:164)
                                                            at android.os.HandlerThread.run(HandlerThread.java:65)
                                                            at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-15 21:22:07.405 2495-2495/? V/FingerprintService: startAuthentication(com.kunzisoft.keepass.libre)
05-15 21:22:07.405 2495-2495/? V/FingerprintService: starting client AuthenticationClient(com.kunzisoft.keepass.libre), initiatedByClient = true)
05-15 21:22:07.411 2495-2495/? W/FingerprintService: client com.kunzisoft.keepass.libre is authenticating...
05-15 21:22:12.218 2495-2495/? V/FingerprintService: onAuthenticated(owner=com.kunzisoft.keepass.libre, id=1404546259, gp=0)
05-15 21:22:12.220 2495-2495/? V/FingerprintService: Done with client: com.kunzisoft.keepass.libre
05-15 21:22:12.230 28528-28528/? E/com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Unable to encrypt data
                                                                                        javax.crypto.IllegalBlockSizeException
                                                                                            at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
                                                                                            at javax.crypto.Cipher.doFinal(Cipher.java:1741)
                                                                                            at com.kunzisoft.keepass.fingerprint.FingerPrintHelper.encryptData(FingerPrintHelper.java:174)
                                                                                            at com.kunzisoft.keepass.password.PasswordActivity$6.onAuthenticationSucceeded(PasswordActivity.java:554)
                                                                                            at android.support.v4.hardware.fingerprint.FingerprintManagerCompat$1.onAuthenticationSucceeded(FingerprintManagerCompat.java:175)
                                                                                            at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:961)
                                                                                            at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:882)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                         Caused by: android.security.KeyStoreException: Key user not authenticated
                                                                                            at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
                                                                                            at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
                                                                                            at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
                                                                                            at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
                                                                                            at javax.crypto.Cipher.doFinal(Cipher.java:1741) 
                                                                                            at com.kunzisoft.keepass.fingerprint.FingerPrintHelper.encryptData(FingerPrintHelper.java:174) 
                                                                                            at com.kunzisoft.keepass.password.PasswordActivity$6.onAuthenticationSucceeded(PasswordActivity.java:554) 
                                                                                            at android.support.v4.hardware.fingerprint.FingerprintManagerCompat$1.onAuthenticationSucceeded(FingerprintManagerCompat.java:175) 
                                                                                            at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:961) 
                                                                                            at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:882) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by J-Jamet** [comment]
Yes maybe the solution on stackoverflow will solve the problem. I'll try to blindly apply a fix and give it to you in comment. What's odd is that he sees the user as unauthenticated when he should be. There may be cases where the authentication is not done correctly, I will analyze it theoretically. If you can implement and test the fixes on your side do not hesitate.

**Comment by gradinaruvasile** [comment]
I am not a developer, but if you can provide a patch i could **try** to apply on the sources and compile the app.

**Comment by J-Jamet** [comment]
No worries, in this case, I'll give you several APKs to install, you will tell me how they react on your device.

**Comment by J-Jamet** [comment]
Can you tell me if this APK [KeePassDX_TEST_2018071001.apk.zip](https://github.com/Kunzisoft/KeePassDX/files/2179802/KeePassDX_TEST_2018071001.apk.zip) solve your problem ?

**Comment by gradinaruvasile** [comment]
Unfortunately not. I get this error (pretty much the same as before):
```
7-10 16:16:49.421  2215  2256 I ActivityManager: Displayed com.kunzisoft.keepass.free/com.kunzisoft.keepass.password.PasswordActivity: +338ms
07-10 16:16:53.441  2215  2215 V FingerprintService: startAuthentication(com.kunzisoft.keepass.free)
07-10 16:16:53.441  2215  2215 V FingerprintService: starting client AuthenticationClient(com.kunzisoft.keepass.free), initiatedByClient = true)
07-10 16:16:53.452  2215  2215 W FingerprintService: client com.kunzisoft.keepass.free is authenticating...
07-10 16:17:06.741  2215  2215 V FingerprintService: onAuthenticated(owner=com.kunzisoft.keepass.free, id=1404546259, gp=0)
07-10 16:17:06.743  2215  2215 V FingerprintService: Done with client: com.kunzisoft.keepass.free
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Unable to encrypt data
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: javax.crypto.IllegalBlockSizeException
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.fingerprint.FingerPrintHelper.encryptData(FingerPrintHelper.java:174)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.password.PasswordActivity$5.onAuthenticationSucceeded(PasswordActivity.java:608)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:961)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:882)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Looper.loop(Looper.java:164)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Caused by: android.security.KeyStoreException: Key user not authenticated
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	... 11 more
```

**Comment by J-Jamet** [comment]
OK, After a few hours of tests, changes and code readings, I made some changes, including:
// KeyGenParameterSpec.builder...
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            builder.setInvalidatedByBiometricEnrollment(false);
        }`
which comes from Magisk and seems to be done to solve the problems of Android N (Lineage 15.1), but not really sure.

Can you test this new APK : 
[KeePassDX_TEST_201807102.apk.zip](https://github.com/Kunzisoft/KeePassDX/files/2181818/KeePassDX_TEST_201807102.apk.zip)

Thank you

**Comment by gradinaruvasile** [comment]
Unfortunately not. I get this error (pretty much the same as before):
```
7-10 16:16:49.421  2215  2256 I ActivityManager: Displayed com.kunzisoft.keepass.free/com.kunzisoft.keepass.password.PasswordActivity: +338ms
07-10 16:16:53.441  2215  2215 V FingerprintService: startAuthentication(com.kunzisoft.keepass.free)
07-10 16:16:53.441  2215  2215 V FingerprintService: starting client AuthenticationClient(com.kunzisoft.keepass.free), initiatedByClient = true)
07-10 16:16:53.452  2215  2215 W FingerprintService: client com.kunzisoft.keepass.free is authenticating...
07-10 16:17:06.741  2215  2215 V FingerprintService: onAuthenticated(owner=com.kunzisoft.keepass.free, id=1404546259, gp=0)
07-10 16:17:06.743  2215  2215 V FingerprintService: Done with client: com.kunzisoft.keepass.free
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Unable to encrypt data
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: javax.crypto.IllegalBlockSizeException
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.fingerprint.FingerPrintHelper.encryptData(FingerPrintHelper.java:174)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.password.PasswordActivity$5.onAuthenticationSucceeded(PasswordActivity.java:608)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:961)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:882)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Looper.loop(Looper.java:164)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Caused by: android.security.KeyStoreException: Key user not authenticated
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-10 16:17:06.747   661   661 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	... 11 more
```

**Comment by J-Jamet** [comment]
So... I don't know what to do, I really thought it was that after the second APK. I compared with Majisk and I don't see any difference. It's really hard to debug without being able to reproduce the problem. :/

**Comment by gradinaruvasile** [comment]
Yes, i double checked, both .apk's produce the same error.
Here is a more complete logcat output without filters:

```
7-13 04:51:40.263  2039  2146 D android.hardware.biometrics.fingerprint@2.0-service: onAcquired(6)
07-13 04:51:40.264  2039  2146 I fpc_tac : fpc_tac_capture_image begin
07-13 04:51:40.267 19984 19984 W FingerprintManager: Invalid acquired message: 6, 200
07-13 04:51:40.357  2039  2146 I fpc_tac : fpc_tac_capture_image end
07-13 04:51:40.357  2039  2146 D fpc_fingerprint_hal: fpc_handle_image_subscription
07-13 04:51:40.357  2039  2146 D android.hardware.biometrics.fingerprint@2.0-service: onAcquired(0)
07-13 04:51:40.358   455   455 E QCOM PowerHAL: Failed to acquire lock.
07-13 04:51:40.462  2039  2146 I fpc_tac : fpc_tac_identify end
07-13 04:51:40.462  2039  2146 D fpc_fingerprint_hal: do_identify fpc_tac_identify bigData result 1, totalTime 104,  matchScore 671, imageQuality 0
07-13 04:51:40.462  2039  2146 D fpc_fingerprint_hal: do_identify fpc_tac_identify result 2 671 1 151106
07-13 04:51:40.462  2039  2146 I fpc_tac : fpc_tac_get_template_id_from_index begin
07-13 04:51:40.464  2039  2146 I fpc_tac : fpc_tac_get_template_id_from_index end
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: authenticated
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->challenge 13836567323113861714
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->authenticator_id 2058867059033153107
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->authenticator_type 33554432
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->timestamp 3577277689607749632
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->user_id 717931940460904659
07-13 04:51:40.468  2039  2146 D fpc_fingerprint_hal: hat->version 0
07-13 04:51:40.468  2039  2146 D android.hardware.biometrics.fingerprint@2.0-service: onAuthenticated(fid=1404546259, gid=0)
07-13 04:51:40.468  2039  2146 I fpc_tac : fpc_tac_end_identify begin
07-13 04:51:40.470  2215  2215 V FingerprintService: onAuthenticated(owner=com.kunzisoft.keepass.libre, id=1404546259, gp=0)
07-13 04:51:40.472  2039  2146 I fpc_tac : fpc_tac_end_identify end
07-13 04:51:40.473  2215  2215 V FingerprintService: Done with client: com.kunzisoft.keepass.libre
07-13 04:51:40.477  1960  1960 E keystore: getAuthToken failed: -5
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Unable to encrypt data
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: javax.crypto.IllegalBlockSizeException
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.fingerprint.FingerPrintHelper.encryptData(FingerPrintHelper.java:174)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.kunzisoft.keepass.password.PasswordActivity$5.onAuthenticationSucceeded(PasswordActivity.java:555)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.support.v4.hardware.fingerprint.FingerprintManagerCompat$1.onAuthenticationSucceeded(FingerprintManagerCompat.java:175)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:961)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:882)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.os.Looper.loop(Looper.java:164)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: Caused by: android.security.KeyStoreException: Key user not authenticated
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-13 04:51:40.479 19984 19984 E com.kunzisoft.keepass.fingerprint.FingerPrintHelper: 	... 12 more
07-13 04:51:40.518  2039  2146 I fpc_fingerprint_hal: workerFunction STATE_NONE
07-13 04:51:40.524  2039  2146 I fpc_fingerprint_hal: workerFunction STATE_IDLE

```

For reference i have tested a few apps that use fingerprint authentication and it seems that all of them have the same output when authenticating.

Example of nextcloud (but it is the same output for my banking app, AndOTP):
```
07-13 04:43:25.373  2039  2146 D android.hardware.biometrics.fingerprint@2.0-service: onAcquired(0)
07-13 04:43:25.374   455   455 E QCOM PowerHAL: Failed to acquire lock.
07-13 04:43:25.488  2039  2146 I fpc_tac : fpc_tac_identify end
07-13 04:43:25.488  2039  2146 D fpc_fingerprint_hal: do_identify fpc_tac_identify bigData result 1, totalTime 114,  matchScore 776, imageQuality 0
07-13 04:43:25.488  2039  2146 D fpc_fingerprint_hal: do_identify fpc_tac_identify result 2 776 1 151106
07-13 04:43:25.488  2039  2146 I fpc_tac : fpc_tac_get_template_id_from_index begin
07-13 04:43:25.491  2039  2146 I fpc_tac : fpc_tac_get_template_id_from_index end
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: authenticated
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->challenge 15275618237556874415
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->authenticator_id 2058867059033153107
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->authenticator_type 33554432
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->timestamp 12976845365302001664
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->user_id 717931940460904659
07-13 04:43:25.495  2039  2146 D fpc_fingerprint_hal: hat->version 0
07-13 04:43:25.495  2039  2146 D android.hardware.biometrics.fingerprint@2.0-service: onAuthenticated(fid=1404546259, gid=0)
07-13 04:43:25.495  2039  2146 I fpc_tac : fpc_tac_end_identify begin
07-13 04:43:25.496  2215  2215 V FingerprintService: onAuthenticated(owner=com.nextcloud.client, id=1404546259, gp=0)
07-13 04:43:25.499  2039  2146 I fpc_tac : fpc_tac_end_identify end
07-13 04:43:25.507 13482 13482 D FingerprintActivity: onPause() ending
07-13 04:43:25.510  2215  2215 V FingerprintService: Done with client: com.nextcloud.client
```

Also here is a more extended

**Comment by J-Jamet** [comment]
I managed to solve the problem, there is better exception handling in version 2.5.0.0beta23. The solution I found is to delete fingerprints from the device and save them again. It seems to be an android bug. Tell me if it works with the new version?

**Comment by ozmium** [comment]
I had this problem recently. KeePassDX version 4.0.8 suddenly just stopped working with the fingerprint unlock, even though all other apps that used Fingerprint unlock were working fine.

I kept seeing "-49" Toast messages popup often, whilst I was typing in the password to unlock the kdbx file.

I tried clearing the encryption keys, using KeyPassDX -> Settings -> Device Unlocking -> Delete encryption keys. This did not work.
 
In the end, I just rebooted the phone and it started working fine again.

**Comment by danysers** [comment]
I don't know if the topic is closed, but I leave my contribution, I had the same error with code -28, I solved it by deleting all the fingerprints that I already had loaded on the device, restarted, and then from KeePassDX, I reloaded the new fingerprints that I wanted, magically it worked and now I can use the biometric data.
