### ISSUE TITLE
Invalid algorithm with Chacha20 and AES-KDF (v3)

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#116]
ChaCha7539-20 requires exactly 12 bytes of IV when Chacha20 and AESKDF (v3) are configured from KeePass XC

```
E/com.kunzisoft.keepass.database.action.LoadDBRunnable: Database can't be read
    java.io.IOException: Invalid algorithm.
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:129)
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:77)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:173)
        at com.kunzisoft.keepass.database.Database.passUrisAsInputStreams(Database.java:152)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:119)
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:107)
        at com.kunzisoft.keepass.database.action.LoadDBRunnable.run(LoadDBRunnable.java:71)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.security.InvalidKeyException: ChaCha7539-20 requires exactly 12 bytes of IV
        at org.spongycastle.jcajce.provider.symmetric.util.BaseStreamCipher.engineInit(BaseStreamCipher.java:269)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2870)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
        at javax.crypto.Cipher.init(Cipher.java:1329)
        at javax.crypto.Cipher.init(Cipher.java:1267)
        at com.kunzisoft.keepass.crypto.engine.ChaCha20Engine.getCipher(ChaCha20Engine.java:52)
        at com.kunzisoft.keepass.crypto.engine.CipherEngine.getCipher(CipherEngine.java:43)
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:127)
        at com.kunzisoft.keepass.database.load.ImporterV4.openDatabase(ImporterV4.java:77) 
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:173) 
        at com.kunzisoft.keepass.database.Database.passUrisAsInputStreams(Database.java:152) 
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:119) 
        at com.kunzisoft.keepass.database.Database.loadData(Database.java:107) 
        at com.kunzisoft.keepass.database.action.LoadDBRunnable.run(LoadDBRunnable.java:71) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by J-Jamet** [comment]
I investigated all day for this issue by doing many tests:

- Creation of a database with KeePass XC, algorithm Chacha20 and AES v3 in KDF. No opening without the KDFParameter because the IV is 16 bytes and not 12.

- Creation of a database with KeePass 2 with Chacha20 and AES. The opening is done correctly without KDFParameter.

The problem therefore comes from KeePass XC which does not respect the 12 bytes for the IV of the Chacha 20 algorithm, see https://keepass.info/help/kb/kdbx_4.html#chacha20

**Comment by J-Jamet** [comment]
**This problem will not be fixed because it is pointing to an outdated version of the database, just select AES-KDFv4 instead of AES-KDFv3 in KeePass XC.**
