### ISSUE TITLE
Crash is a search is performed / Search refactoring

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#1219]
**Describe the bug**
A crash is performed after a click on the search button

```
2022-01-28 11:52:14.545 16937-16937/com.kunzisoft.keepass.pro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kunzisoft.keepass.pro, PID: 16937
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.getPadding(android.graphics.Rect)' on a null object reference
        at androidx.appcompat.widget.SearchView.adjustDropDownSizeAndPosition(SearchView.java:1380)
        at androidx.appcompat.widget.SearchView$4.onLayoutChange(SearchView.java:383)
        at android.view.View.layout(View.java:23161)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1669)
        at androidx.appcompat.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1658)
        at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1433)
        at androidx.appcompat.widget.SearchView.onLayout(SearchView.java:839)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at androidx.appcompat.widget.Toolbar.layoutChildLeft(Toolbar.java:2118)
        at androidx.appcompat.widget.Toolbar.onLayout(Toolbar.java:1933)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
        at android.view.View.layout(View.java:23143)
        at android.view.ViewGroup.layout(ViewGroup.java:6412)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3684)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
2022-01-28 11:52:14.545 16937-16937/com.kunzisoft.keepass.pro E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**To Reproduce**
Simply click on the search button
or activate the auto focus on search setting

**Expected behavior**
Search works without crash

**KeePassDX (please complete the following information):**
 - Version: 3.2.0 Beta1

**Comment by J-Jamet** [comment]
No KeePassDX code is in the log, it seems to be a problem of the searchView because with a replacement by the activity search, works fine.

A workaround will be done in version 3.2.0 beta 2 and a refactoring of the search is in progress.

**Comment by J-Jamet** [comment]
The problem simply comes from a style not recognized by the SearchView....
https://stackoverflow.com/questions/22295138/android-action-bar-searchview-nullpointerexception-adjustdropdownsizeandposition
