### ISSUE TITLE
[Android 13 Beta 1] When unlocking a database via autofill, crashes in MainCredentialActivity.onValidateSpecialMode

### ISSUE THREAD

**Issue by chenxiaolong** [Kunzisoft/KeePassDX#1321]
**Describe the bug**

On Android 13 Beta 1 (Pixel 6 Pro), unlocking a database via the `Sign in with KeePassDX` autofill entry, `MainCredentialActivity` crashes in the `onValidateSpecialMode` method. This does not happen if the database is already unlocked--autofill works perfectly fine in that case.

**To Reproduce**

1. Ensure the database is locked
2. On a login form, pick the `Sign in with KeePassDX` autofill entry
3. Select the database to unlock (I have 3 databases, none of them starred)
4. The unlocking progress dialog appears and then KeePassDX crashes

**Expected behavior**

KeePassDX should not crash in this scenario.

**KeePass Database**

 - Created with: KeePassXC
 - Version: KDBX 4.0
 - Location: Local file
 - File provider (`content://` URI): `content://com/android.externalstorage.documents/document/primary%3AKeePass%2Fpwdb.kdbx`
 - Size: 2.7 MiB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 3.4.3
 - Build: `com.kunzisoft.keepass.free` package with Contributor Pro
  - Language: US English

**Android:**

 - Device: Pixel 6 Pro
 - Version: 13 Beta 1

**Additional context**

<details>
<summary>Logs and stack trace (click to expand):</summary>

```
                UriUtil  D  Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3AKeePass%2Fpwdb.kdbx, modeFlags=3, persistedTime=1647478864769}
     InputMethodManager  D  showSoftInput() view=com.google.android.material.textfield.TextInputEditText{338b312 VFED..CL. .F....ID 0,0-1230,167 #7f0902ab app:id/password_text_view aid=1073741825} flags=1 reason=SHOW_SOFT_INPUT
        AssistStructure  I  Flattened final assist data: 5652 bytes, containing 1 windows, 36 views
       InsetsController  D  show(ime(), fromIme=true)
         OpenGLRenderer  D  endAllActiveAnimators on 0xb400006f21c3bd00 (RippleDrawable) with handle 0xb400006e31be9920
ile.input.DatabaseInput  D  Start retrieving database key...
fill.KeeAutofillService  D  onConnected
                         D  onDisconnected
ile.input.DatabaseInput  D  Stop retrieving database key... 2862 ms
                         D  Start decrypting database content...
                         D  Stop retrieving database content... 503 ms
                UriUtil  D  Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3AKeePass%2Fpwdb.kdbx, modeFlags=3, persistedTime=1647478864769}
utofill.StructureParser  D  Autofill applicationId: com.machiav3lli.backup
                         D  Autofill applicationId: com.machiav3lli.backup
                         D  Autofill password android text type: 0x00000081
atibilityChangeReporter  D  Compat change id reported: 147798919; UID 10296; state: ENABLED
.MainCredentialActivity  D  Successed Autofill auth.
                UriUtil  D  Check URI permission : UriPermission {uri=content://com.android.externalstorage.documents/document/primary%3AKeePass%2Fpwdb.kdbx, modeFlags=3, persistedTime=1647478864769}
TaskNotificationService  I  Database file saved SnapFileDatabaseInfo(fileUri=content://com.android.externalstorage.documents/document/primary%3AKeePass%2Fpwdb.kdbx, exists=true, lastModification=1651615582000, size=2857237)
  BiometricPromptCompat  E  Unable to cancel authentication. BiometricFragment not found.
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.kunzisoft.keepass.free, PID: 31527
                         E  java.lang.IllegalStateException: Can't Parcel a ParceledListSlice more than once
                         E      at android.content.pm.BaseParceledListSlice.writeToParcel(BaseParceledListSlice.java:164)
                         E      at android.content.pm.ParceledListSlice.writeToParcel(ParceledListSlice.java:35)
                         E      at android.os.Parcel.writeParcelable(Parcel.java:2537)
                         E      at android.service.autofill.FillResponse.writeToParcel(FillResponse.java:1002)
                         E      at android.os.Parcel.writeParcelable(Parcel.java:2537)
                         E      at android.os.Parcel.writeValue(Parcel.java:2438)
                         E      at android.os.Parcel.writeValue(Parcel.java:2315)
                         E      at android.os.Parcel.writeArrayMapInternal(Parcel.java:1264)
                         E      at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1775)
                         E      at android.os.Bundle.writeToParcel(Bundle.java:1357)
                         E      at android.os.Parcel.writeBundle(Parcel.java:1333)
                         E      at android.content.Intent.writeToParcel(Intent.java:11482)
                         E      at android.os.Parcel.writeTypedObject(Parcel.java:2156)
                         E      at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1362)
                         E      at android.app.ActivityClient.finishActivity(ActivityClient.java:155)
                         E      at android.app.Activity.finish(Activity.java:6645)
                         E      at android.app.Activity.finish(Activity.java:6662)
                         E      at com.kunzisoft.keepass.activities.MainCredentialActivity.onValidateSpecialMode(MainCredentialActivity.kt:374)
                         E      at com.kunzisoft.keepass.activities.MainCredentialActivity$launchGroupActivityIfLoaded$1.invoke(MainCredentialActivity.kt:364)
                         E      at com.kunzisoft.keepass.activities.MainCredentialActivity$launchGroupActivityIfLoaded$1.invoke(MainCredentialActivity.kt:362)
                         E      at com.kunzisoft.keepass.activities.GroupActivity$Companion$launch$6$1.invoke(GroupActivity.kt:1701)
                         E      at com.kunzisoft.keepass.activities.GroupActivity$Companion$launch$6$1.invoke(GroupActivity.kt:1695)
                         E      at com.kunzisoft.keepass.database.search.SearchHelper$Companion.checkAutoSearchInfo(SearchHelper.kt:161)
                         E      at com.kunzisoft.keepass.activities.GroupActivity$Companion$launch$6.invoke(GroupActivity.kt:1695)
                         E      at com.kunzisoft.keepass.activities.GroupActivity$Companion$launch$6.invoke(GroupActivity.kt:1609)
                         E      at com.kunzisoft.keepass.activities.helpers.EntrySelectionHelper.doSpecialAction(EntrySelectionHelper.kt:173)
                         E      at com.kunzisoft.keepass.activities.GroupActivity$Companion.launch(GroupActivity.kt:1609)
                         E      at com.kunzisoft.keepass.activities.MainCredentialActivity.launchGroupActivityIfLoaded(MainCredentialActivity.kt:362)
                         E      at com.kunzisoft.keepass.activities.MainCredentialActivity.onDatabaseActionFinished(MainCredentialActivity.kt:266)
                         E      at com.kunzisoft.keepass.activities.legacy.DatabaseActivity$onCreate$2.invoke(DatabaseActivity.kt:35)
                         E      at com.kunzisoft.keepass.activities.legacy.DatabaseActivity$onCreate$2.invoke(DatabaseActivity.kt:34)
                         E      at com.kunzisoft.keepass.database.action.DatabaseTaskProvider$actionTaskListener$1.onStopAction(DatabaseTaskProvider.kt:138)
                         E      at com.kunzisoft.keepass.services.DatabaseTaskNotificationService$onStartCommand$2$3.invoke(DatabaseTaskNotificationService.kt:292)
                         E      at com.kunzisoft.keepass.services.DatabaseTaskNotificationService$onStartCommand$2$3.invoke(DatabaseTaskNotificationService.kt:268)
                         E      at com.kunzisoft.keepass.services.DatabaseTaskNotificationService$executeAction$2$1$1.invokeSuspend(DatabaseTaskNotificationService.kt:510)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                         E      at android.os.Handler.handleCallback(Handler.java:942)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7844)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                Process  I  Sending signal. PID: 31527 SIG: 9
```
</details>

**Comment by chenxiaolong** [comment]
The issue seems to be `Activity.finish()` being called twice, once from `DatabaseModeActivity.onValidateSpecialMode` and again in `MainCredentialsActivity.onValidateSpecialMode`. I'm not sure if this is an appropriate fix, but applying this workaround makes it no longer crash:

```diff
diff --git a/app/src/main/java/com/kunzisoft/keepass/activities/MainCredentialActivity.kt b/app/src/main/java/com/kunzisoft/keepass/activities/MainCredentialActivity.kt
index bc4e50870..a2374d29e 100644
--- a/app/src/main/java/com/kunzisoft/keepass/activities/MainCredentialActivity.kt
+++ b/app/src/main/java/com/kunzisoft/keepass/activities/MainCredentialActivity.kt
@@ -371,7 +371,9 @@ class MainCredentialActivity : DatabaseModeActivity(), AdvancedUnlockFragment.Bu

     override fun onValidateSpecialMode() {
         super.onValidateSpecialMode()
-        finish()
+        if (!isFinishing) {
+            finish()
+        }
     }

     override fun onCancelSpecialMode() {
```

**Comment by chenxiaolong** [comment]
I can confirm commit 5a30d9d2b5f9e364e679251b62017874e80abb6d fixes the issue for me. Thanks for the quick fix!
