### ISSUE TITLE
Autofill crash on Android 13

### ISSUE THREAD

**Issue by mpldr** [Kunzisoft/KeePassDX#1649]
**Describe the bug**

**To Reproduce**

1. Go to any website with a password field
2. Click on said password field
3. KeepassDX crashed

**Expected behavior**

Not sure what the reason is, could it be connected to me using Simple Keyboard? KeePassDX works as expected when used directly..

**KeePass Database**

 - Created with: KeePass XC on Linux
 - Version: 2
 - Location: local file, synchronised via syncthing
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary%3AKeepass%2Fpasswords.kdbx
 - Size: 9.4 MiB
 - Contains attachment: Yes

**KeePassDX:**

 - Version: 4.0.2
 - Build: Play Store
 - Language: English

**Android:**

 - Device: Google Pixel 5
 - Android: GrapheneOS
 - Version: 13

**Additional context**

 - Browser for Autofill: Firefox on Android

```
type: crash
osVersion: google/redfin/redfin:13/TQ3A.230901.001/2023091800:user/release-keys
package: com.kunzisoft.keepass.free:125
process: com.kunzisoft.keepass.free
processUptime: 399 + 741 ms
installer: com.android.vending

java.lang.RuntimeException: Not allowed to write file descriptors here
	at android.os.Parcel.nativeAppendFrom(Native Method)
	at android.os.Parcel.appendFrom(Parcel.java:760)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1787)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1336)
	at android.widget.inline.InlinePresentationSpec.writeToParcel(InlinePresentationSpec.java:199)
	at android.os.Parcel.writeParcelable(Parcel.java:2540)
	at android.os.Parcel.writeParcelableList(Parcel.java:2110)
	at android.view.inputmethod.InlineSuggestionsRequest.writeToParcel(InlineSuggestionsRequest.java:420)
	at android.os.Parcel.writeParcelable(Parcel.java:2540)
	at com.kunzisoft.keepass.autofill.CompatInlineSuggestionsRequest.writeToParcel(CompatInlineSuggestionsRequest.kt:65)
	at android.os.Parcel.writeParcelable(Parcel.java:2540)
	at android.os.Parcel.writeValue(Parcel.java:2441)
	at android.os.Parcel.writeValue(Parcel.java:2318)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1267)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1804)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1336)
	at android.os.Parcel.writeValue(Parcel.java:2435)
	at android.os.Parcel.writeValue(Parcel.java:2325)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1267)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1804)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1336)
	at android.content.Intent.writeToParcel(Intent.java:11608)
	at android.os.Parcel.writeTypedObject(Parcel.java:2159)
	at android.os.Parcel.writeTypedArray(Parcel.java:2139)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:5895)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:495)
	at android.app.PendingIntent.getActivity(PendingIntent.java:476)
	at android.app.PendingIntent.getActivity(PendingIntent.java:440)
	at com.kunzisoft.keepass.activities.AutofillLauncherActivity$Companion.getPendingIntentForSelection(AutofillLauncherActivity.kt:228)
	at com.kunzisoft.keepass.autofill.KeeAutofillService.showUIForEntrySelection(KeeAutofillService.kt:165)
	at com.kunzisoft.keepass.autofill.KeeAutofillService.access$showUIForEntrySelection(KeeAutofillService.kt:50)
	at com.kunzisoft.keepass.autofill.KeeAutofillService$launchSelection$3.invoke(KeeAutofillService.kt:148)
	at com.kunzisoft.keepass.autofill.KeeAutofillService$launchSelection$3.invoke(KeeAutofillService.kt:132)
	at com.kunzisoft.keepass.database.helper.SearchHelper.checkAutoSearchInfo(SearchHelper.kt:54)
	at com.kunzisoft.keepass.autofill.KeeAutofillService.launchSelection(KeeAutofillService.kt:132)
	at com.kunzisoft.keepass.autofill.KeeAutofillService.access$launchSelection(KeeAutofillService.kt:50)
	at com.kunzisoft.keepass.autofill.KeeAutofillService$onFillRequest$2$1.invoke(KeeAutofillService.kt:117)
	at com.kunzisoft.keepass.autofill.KeeAutofillService$onFillRequest$2$1.invoke(KeeAutofillService.kt:109)
	at com.kunzisoft.keepass.utils.WebDomain$getConcreteWebDomain$1.invokeSuspend(WebDomain.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c1edcc5, Dispatchers.Main]

```

**Comment by J-Jamet** [comment]
I don't have any bug reports of this type on the Play Store, I've already resolved a bug of this type due to the poorly implemented system autofill on some Android 13, but here I don't even see what I can do since no file descriptor is sent. Are you sure it's not coming from an APK on the net, because if it's been modified it could retrieve your information.

**Comment by J-Jamet** [comment]
Just added a code to capture exception
