### ISSUE TITLE
Android 4.0 seems dropped but not in published app 

### ISSUE THREAD

**Issue by victorKH** [Kunzisoft/KeePassDX#1687]
I run version 3.0.2 just fine on Android 4.2 but it  using DocumentUI which present on Android 4.4+ (I just open kbdx with es explorer in my case).
When I install (successfully) and try to run app version 4.x.x it's just crashed. It is seems that starting from 4.0 app dropped support of android 4.0 or some app dependencies are dropped support of Android 4.0.

Please update min SDK to correct supported Android version in published app or review unsupported pieces of code.

**Comment by J-Jamet** [comment]
Version 3.0.2 is a very old version.
I've just installed the application version 4.0.5 on an Android Ice Cream Sandwich 4.0.4 (API 15) and I have no crashes.

On the other hand, you right, you need a file browser compatible with SAF Intent, and I don't know if there's one compatible before KitKat. But it doesn't crash, and that doesn't stop anyone from creating a compatible file manager for older devices.

**Comment by J-Jamet** [comment]
I'll just point out that the published application requires Android 4.4. It'll be easier for everyone.

**Comment by victorKH** [comment]
If you don't want to drop Android 4.0 - there are plenty of simple File Manager classes OR just user opens kbdx from any preinstalled or 3rd party app (like I do with ES Explorer).

There some logcat info for version 4.0.5 from GP.

First records I think related to "if (sdk version)" statements
But last records (before app died) related to Database kotlin functions. May be there problem.
Not all devices support sqlite some functionality - so some apps includes native sqlite libs if needed more device compatibility.

---- 11.11.2023 15:53:29 ----

11-11 15:53:12.712 13849 13849 I MultiDex: MultiDexExtractor(/data/app/com.kunzisoft.keepass.free-1.apk, /data/data/com.kunzisoft.keepass.free/code_cache/secondary-dexes)

11-11 15:53:12.712 13849 13849 I MultiDex: Blocking on lock /data/data/com.kunzisoft.keepass.free/code_cache/secondary-dexes/MultiDex.lock

11-11 15:53:12.712 13849 13849 I MultiDex: /data/data/com.kunzisoft.keepass.free/code_cache/secondary-dexes/MultiDex.lock locked

11-11 15:53:12.712 13849 13849 I MultiDex: MultiDexExtractor.load(/data/app/com.kunzisoft.keepass.free-1.apk, false, )

11-11 15:53:13.052 13849 13849 I dalvikvm: Could not find method android.os.Bundle.getParcelable, referenced from method com.kunzisoft.keepass.activities.FileDatabaseSelectActivity.onCreate

11-11 15:53:13.052 13849 13849 I dalvikvm: Could not find method android.os.Bundle.getParcelable, referenced from method com.kunzisoft.keepass.activities.FileDatabaseSelectActivity.onDatabaseActionFinished

11-11 15:53:13.052 13849 13849 I dalvikvm: Could not find method android.os.Bundle.getParcelable, referenced from method com.kunzisoft.keepass.activities.FileDatabaseSelectActivity.onDatabaseActionFinished

11-11 15:53:13.243 13849 13849 I dalvikvm: Could not find method android.content.Intent.getParcelableExtra, referenced from method com.kunzisoft.keepass.activities.helpers.EntrySelectionHelper.retrieveRegisterInfoFromIntent

11-11 15:53:13.243 13849 13849 I dalvikvm: Could not find method android.content.Intent.getParcelableExtra, referenced from method com.kunzisoft.keepass.activities.helpers.EntrySelectionHelper.retrieveSearchInfoFromIntent

11-11 15:53:13.683 13849 13849 I dalvikvm: Could not find method android.content.Context.getNoBackupFilesDir, referenced from method com.kunzisoft.keepass.utils.UriHelperKt.getBinaryDir

11-11 15:53:13.683 13849 13849 I dalvikvm: Could not find method android.content.pm.PackageManager$PackageInfoFlags.of, referenced from method com.kunzisoft.keepass.utils.UriHelperKt.getPackageInfoCompat

11-11 15:53:13.683 13849 13849 I dalvikvm: Could not find method android.content.pm.PackageManager$ResolveInfoFlags.of, referenced from method com.kunzisoft.keepass.utils.UriHelperKt.queryIntentActivitiesCompat

11-11 15:53:13.893 13849 13849 E dalvikvm: Could not find class 'android.view.autofill.AutofillManager', referenced from method com.kunzisoft.keepass.settings.NestedAppSettingsFragment.onCreateFormFillingPreference

11-11 15:53:13.893 13849 13849 W dalvikvm: VFY: unable to resolve const-class 155 (Landroid/view/autofill/AutofillManager;) in Lcom/kunzisoft/keepass/settings/NestedAppSettingsFragment;

11-11 15:53:13.893 13849 13849 E dalvikvm: Could not find class 'android.view.autofill.AutofillManager', referenced from method com.kunzisoft.keepass.settings.NestedAppSettingsFragment.onResume

11-11 15:53:13.893 13849 13849 W dalvikvm: VFY: unable to resolve const-class 155 (Landroid/view/autofill/AutofillManager;) in Lcom/kunzisoft/keepass/settings/NestedAppSettingsFragment;

11-11 15:53:13.913 13849 13849 I dalvikvm: Could not find method android.content.ContentResolver.getPersistedUriPermissions, referenced from method com.kunzisoft.keepass.utils.UriUtil.persistUriPermission

11-11 15:53:13.913 13849 13849 I dalvikvm: Could not find method android.content.Intent.getParcelableExtra, referenced from method com.kunzisoft.keepass.utils.UriUtil.getUri

11-11 15:53:14.013 13849 13849 E AndroidRuntime: 	at com.kunzisoft.keepass.utils.IOActionTask.execute(IOActionTask.kt:34)

11-11 15:53:14.013 13849 13849 E AndroidRuntime: 	at com.kunzisoft.keepass.viewmodels.DatabaseFilesViewModel.checkDefaultDatabase(DatabaseFilesViewModel.kt:41)

11-11 15:53:14.013 13849 13849 E AndroidRuntime: 	at com.kunzisoft.keepass.viewmodels.DatabaseFilesViewModel.loadListOfDatabases(DatabaseFilesViewModel.kt:65)

11-11 15:53:14.013 13849 13849 E AndroidRuntime: 	at com.kunzisoft.keepass.activities.FileDatabaseSelectActivity.onResume(FileDatabaseSelectActivity.kt:361)

11-11 15:53:21.781   552   858 I ActivityManager: Process com.kunzisoft.keepass.free (pid 13849) (adj 1) has died.

---- 11.11.2023 15:53:29 ----

**Comment by J-Jamet** [comment]
I am upgrading the minimum version to 4.4 and soon to 5.0, so there will be no more issues of this kind.
