### ISSUE TITLE
Crash on vivo

### ISSUE THREAD

**Issue by cat0x1f** [Kunzisoft/KeePassDX#1761]
Due to my limited proficiency in English, the information provided below has been translated by ChatGPT.

**Describe the bug**

I have successfully reproduced a particular issue on a Vivo phone running Android 14. Upon performing a long-press on a text box within the application, it results in a crash, reverting to the password vault's unlock screen.

KeePassDX version: 4.0.5. I have already reported this issue to Vivo; however, I also hope that you can directly address and resolve it.

**KeePassDX:**

 - Version: any version
 - Build: any version
 - Language: Chinese

**Android:**

 - Device: vivo iQOO Neo 9
 - Version: Android 14

https://github.com/Kunzisoft/KeePassDX/assets/72690879/eb9b78ab-c1b9-41c5-8c30-ae40ad4c32c2

**Comment by shuvashish76** [comment]
請使用谷歌翻譯而不是ChatGPT。
在我的設備上無法重現。 可以分享一下崩潰日誌嗎？
例如，使用這些應用程式來記錄崩潰情況。
- [Scoop](https://f-droid.org/packages/taco.scoop/) ([請參閱說明](https://github.com/TacoTheDank/Scoop/wiki))
- [LogFox](https://f-droid.org/packages/com.f0x1d.logfox/)

**Comment by cat0x1f** [comment]
崩溃日志如下：
The crash log is as follows:

```
FATAL EXCEPTION: main
Process: com.kunzisoft.keepass.libre, PID: 1747
android.view.InflateException: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Error inflating class ImageButton
Caused by: android.view.InflateException: Binary XML file line #18 in android:layout/floating_popup_overflow_button: Error inflating class ImageButton
Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState
	at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280)
	at android.view.View.applyBackgroundTint(View.java:25984)
	at android.view.View.setBackgroundTintList(View.java:25886)
	at androidx.core.view.ViewCompat$Api21Impl.setBackgroundTintList(ViewCompat.java:4953)
	at androidx.core.view.ViewCompat.setBackgroundTintList(ViewCompat.java:3029)
	at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:65)
	at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:83)
	at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:73)
	at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:253)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:168)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1678)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1729)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1126)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1062)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:681)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:552)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.internal.widget.FtSlidePanelLayout.createRightButton(FtSlidePanelLayout.java:1059)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:217)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:181)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:177)
	at com.android.internal.widget.FtSlidePanelLayout.<init>(FtSlidePanelLayout.java:173)
	at com.android.internal.widget.floatingtoolbar.VivoLocalFloatingToolbarPopup.createSlidePanel(VivoLocalFloatingToolbarPopup.java:1297)
	at com.android.internal.widget.floatingtoolbar.VivoLocalFloatingToolbarPopup.<init>(VivoLocalFloatingToolbarPopup.java:298)
	at com.vivo.VivoSystemFrameworkFactoryImpl.createVivoLocalFloatingToolbarPopup(VivoSystemFrameworkFactoryImpl.java:738)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbarPopup.createVivoInstance(FloatingToolbarPopup.java:114)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbarPopup.createInstance(FloatingToolbarPopup.java:105)
	at com.android.internal.widget.floatingtoolbar.FloatingToolbar.<init>(FloatingToolbar.java:121)
	at com.android.internal.policy.DecorView.createFloatingActionMode(DecorView.java:2441)
	at com.android.internal.policy.DecorView.createActionMode(DecorView.java:2290)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1172)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:1129)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1058)
	at android.view.View.startActionMode(View.java:7978)
	at android.widget.Editor.startInsertionActionMode(Editor.java:2708)
	at android.widget.Editor.performLongClick(Editor.java:1618)
	at android.widget.TextView.performLongClick(TextView.java:15543)
	at android.view.View.performLongClick(View.java:7829)
	at android.view.View$CheckForLongPress.run(View.java:30676)
	at android.os.Handler.handleCallback(Handler.java:1013)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9173)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```

**Comment by J-Jamet** [comment]
The crash is not carried out on KeePassDX code, but on Vivo custom code: 

Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable$LayerState cannot be cast to android.graphics.drawable.VivoListViewSelectorDrawable$ListViewSelectorState
	at android.graphics.drawable.VivoListViewSelectorDrawable.mutate(VivoListViewSelectorDrawable.java:280)
