### ISSUE TITLE
Unable to load database

### ISSUE THREAD

**Issue by hanndecl** [Kunzisoft/KeePassDX#359]
When trying to open a database (created with keepass v2.42 windows and correctly working), I'm getting the following error. (KeePassDX version 2.5.0.0beta23) (Android 9.0 device)

Could you explain to me how I can open this database? 

```
019-10-06 10:19:41.942 12975-13133/? E/com.kunzisoft.keepass.database.action.LoadDatabaseRunnable: Could not load your database.
    java.io.IOException: precondition: START_TAG (position:END_TAG </Binary>@35:2029 in java.io.InputStreamReader@7829763) 
        at com.kunzisoft.keepass.database.file.load.ImporterV4.readXmlStreamed(ImporterV4.kt:280)
        at com.kunzisoft.keepass.database.file.load.ImporterV4.openDatabase(ImporterV4.kt:192)
        at com.kunzisoft.keepass.database.element.Database.loadData(Database.kt:266)
        at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.run(LoadDatabaseRunnable.kt:58)
        at com.kunzisoft.keepass.database.action.ProgressDialogThread$ActionRunnableAsyncTask.doInBackground(ProgressDialogThread.kt:74)
        at com.kunzisoft.keepass.database.action.ProgressDialogThread$ActionRunnableAsyncTask.doInBackground(ProgressDialogThread.kt:60)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by J-Jamet** [comment]
The first thing is to identify why this exception is thrown. Do you read your file in remote or from the memory of your device? Does your database have attachments?

**Comment by hanndecl** [comment]
The database has 3 binary attachements and was read from the memory of the device.

**Comment by J-Jamet** [comment]
Okay, I will try to recreate a database under the same conditions to reproduce the problem.

**Comment by dadosch** [comment]
Same/similar Problem here
```
Datenbank nicht lesbar.
com.kunzisoft.keepass.database.exception.InvalidDBException
	at com.kunzisoft.keepass.database.file.load.ImporterV4.openDatabase(ImporterV4.kt:167)
	at com.kunzisoft.keepass.database.element.Database.loadData(Database.kt:266)
	at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.run(LoadDatabaseRunnable.kt:58)
	at com.kunzisoft.keepass.database.action.ProgressDialogThread$ActionRunnableAsyncTask.doInBackground(ProgressDialogThread.kt:74)
	at com.kunzisoft.keepass.database.action.ProgressDialogThread$ActionRunnableAsyncTask.doInBackground(ProgressDialogThread.kt:60)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by J-Jamet** [comment]
@dadosch This is not the same problem. Your exception comes from an invalid file header.
The @hanndecl exception comes from the strem reader in the XML. 
I will make better error messages for the next update.
@dadosch you should open a new issue for your problem but it looks like your file is just corrupted.

**Comment by J-Jamet** [comment]
Unfortunately I can not reproduce the problem. I have added a better reading method for the XmlPullParser in prevention, but I can not do better without debugging. https://android-developers.googleblog.com/2011/12/watch-out-for-xmlpullparsernexttext.html

**Comment by hanndecl** [comment]
In the mean while I exported my database in an XML format and re-imported the xml in a new kdbx file and the 'problem' was gone. When I was importing a kdbx file into another kdbx file the problem was still there.

Because I can not give you a reproducer I will close the issue. Thanks for investiguating!
