### ISSUE TITLE
App crashes when loading database in 2.9.11 version

### ISSUE THREAD

**Issue by GreatNewHope** [Kunzisoft/KeePassDX#870]
**Describe the bug**

java.lang.NoSuchMethodError: No static method decodeHex(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.kunzisoft.keepass.database.element.database.DatabaseKDBX.checkKeyFileHash(DatabaseKDBX.kt:480)
	at com.kunzisoft.keepass.database.element.database.DatabaseKDBX.loadXmlKeyFile(DatabaseKDBX.kt:452)
	at com.kunzisoft.keepass.database.element.database.DatabaseVersioned.getFileKey(DatabaseVersioned.kt:134)
	at com.kunzisoft.keepass.database.element.database.DatabaseVersioned.getCompositeKey(DatabaseVersioned.kt:93)
	at com.kunzisoft.keepass.database.element.database.DatabaseKDBX.getMasterKey(DatabaseKDBX.kt:331)
	at com.kunzisoft.keepass.database.element.database.DatabaseVersioned.retrieveMasterKey(DatabaseVersioned.kt:88)
	at com.kunzisoft.keepass.database.file.input.DatabaseInputKDBX$openDatabase$1.invoke(DatabaseInputKDBX.kt:103)
	at com.kunzisoft.keepass.database.file.input.DatabaseInputKDBX$openDatabase$1.invoke(DatabaseInputKDBX.kt:66)
	at com.kunzisoft.keepass.database.file.input.DatabaseInputKDBX.openDatabase(DatabaseInputKDBX.kt:136)
	at com.kunzisoft.keepass.database.file.input.DatabaseInputKDBX.openDatabase(DatabaseInputKDBX.kt:102)
	at com.kunzisoft.keepass.database.element.Database$loadData$3.invoke(Database.kt:408)
	at com.kunzisoft.keepass.database.element.Database$loadData$3.invoke(Database.kt:53)
	at com.kunzisoft.keepass.database.element.Database.readDatabaseStream(Database.kt:359)
	at com.kunzisoft.keepass.database.element.Database.loadData(Database.kt:397)
	at com.kunzisoft.keepass.database.action.LoadDatabaseRunnable.onActionRun(LoadDatabaseRunnable.kt:54)
	at com.kunzisoft.keepass.tasks.ActionRunnable.run(ActionRunnable.kt:35)
	at com.kunzisoft.keepass.notifications.DatabaseTaskNotificationService$executeAction$2$invokeSuspend$$inlined$apply$lambda$1.invokeSuspend(DatabaseTaskNotificationService.kt:433)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**To Reproduce**
Just a regular keyfile + password unlock

**Expected behavior**
Open database and not crash

**KeePass Database**
 - Created with: Windows KeePass 2.47
 - Version: [e.g. 2]
 - Location: Remote file retrieved with GDrive app
 - Size: 5k
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.9.11
 - Build: Latest
 - Language: spanish

**Android (please complete the following information):**
 - Device: Xiaomi Redmi 4x
 - Version: miui 11

**Comment by J-Jamet** [comment]
Same as https://github.com/Kunzisoft/KeePassDX/issues/864

Can you build the develop branch and tell if the problem is solved for your device?

**Comment by GreatNewHope** [comment]
🎊  It works!!! 🎊 

Thank very very much 😄

**Comment by J-Jamet** [comment]
Nice. I will release the new version shortly.
