### ISSUE TITLE
Application Crash due to ClassCastException (with crash logs)

### ISSUE THREAD

**Issue by mage1k99** [Kunzisoft/KeePassDX#986]
**Describe the bug**
After unlocking the database when I navigate to list of passwords, from a selected password for certain entries the application crashes.
- This occurs on some password entries only 
- Common thing between the entries that makes application crash is **ICON**

**To Reproduce**
1. Open app
2. unlock using biometics (fingerprint)
3. view a password entry
4. go back to list of password entries by pressing back button
5. entries with icon (favicon) makes the app crash with typecast error

**Expected behavior**
Navigate back to list of passwords

**KeePass Database**
 - Created with: KeePass DX (Android)
 - Version: KeePass 2 - KDBX4.0
 - Location: Local file
 - Size: 261.54KB
 - Contains attachment: YES

**KeePassDX (please complete the following information):**
 - Version: 2.10.0
 - Build: Free
 - Language: English

**Android (please complete the following information):**
 - Device: Redmi K20 Pro ( raphael )
 - Version: 10

**Additional context**
Crash logs
```log
time: 1620589072479
msg: java.lang.ClassCastException: Cannot cast com.kunzisoft.keepass.database.element.CustomDataItem to com.kunzisoft.keepass.database.element.CustomData
stacktrace: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7129, result=32, data=Intent { (has extras) }} to activity {com.kunzisoft.keepass.free/com.kunzisoft.keepass.activities.GroupActivity}: java.lang.ClassCastException: Cannot cast com.kunzisoft.keepass.database.element.CustomDataItem to com.kunzisoft.keepass.database.element.CustomData
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4847)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4888)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.ClassCastException: Cannot cast com.kunzisoft.keepass.database.element.CustomDataItem to com.kunzisoft.keepass.database.element.CustomData
	at java.lang.Class.cast(Class.java:2446)
	at com.kunzisoft.keepass.utils.ParcelableUtil.readStringParcelableMap(ParcelableUtil.kt:79)
	at com.kunzisoft.keepass.database.element.CustomData.<init>(CustomData.kt:20)
	at com.kunzisoft.keepass.database.element.CustomData$CREATOR.createFromParcel(CustomData.kt:59)
	at com.kunzisoft.keepass.database.element.CustomData$CREATOR.createFromParcel(CustomData.kt:57)
	at android.os.Parcel.readParcelable(Parcel.java:2973)
	at com.kunzisoft.keepass.database.element.entry.EntryKDBX.<init>(EntryKDBX.kt:74)
	at com.kunzisoft.keepass.database.element.entry.EntryKDBX$Companion$CREATOR$1.createFromParcel(EntryKDBX.kt:382)
	at com.kunzisoft.keepass.database.element.entry.EntryKDBX$Companion$CREATOR$1.createFromParcel(EntryKDBX.kt:380)
	at android.os.Parcel.readParcelable(Parcel.java:2973)
	at com.kunzisoft.keepass.database.element.Entry.<init>(Entry.kt:83)
	at com.kunzisoft.keepass.database.element.Entry$Companion$CREATOR$1.createFromParcel(Entry.kt:493)
	at com.kunzisoft.keepass.database.element.Entry$Companion$CREATOR$1.createFromParcel(Entry.kt:491)
	at android.os.Parcel.readParcelable(Parcel.java:2973)
	at android.os.Parcel.readValue(Parcel.java:2866)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.getParcelable(Bundle.java:951)
	at android.content.Intent.getParcelableExtra(Intent.java:7967)
	at com.kunzisoft.keepass.activities.fragments.ListNodesFragment.onActivityResult(ListNodesFragment.kt:389)
	at com.kunzisoft.keepass.activities.GroupActivity.onActivityResult(GroupActivity.kt:1192)
	at android.app.Activity.dispatchActivityResult(Activity.java:8131)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4840)
	... 11 more
```
 - Browser for Autofill: Chrome 90.0.4430.93

**Comment by mage1k99** [comment]
you can view the crash log by visiting https://del.dog/dadadjajndan.txt

**Comment by J-Jamet** [comment]
Oh indeed, thank you for this very complete description. I'll fix the problem and make a release with version 2.10.1.

**Comment by J-Jamet** [comment]
The problem comes from custom data in entry. It is possible that it crashes if a value is null, so it can't be cast. I upload a test version on the beta PlayStore, you'll tell me if it solves the issue.

**Comment by J-Jamet** [comment]
In fact it was a typing error, I did not pay attention, it is a CustomDataItem in the CustomData class.
